/* Hello Everyone
   My name is Lavanya Shinde.
   I am enrolled in Oasis Infobyte Internship Program in Java Programming Domain.
  
   This is a project named “Guess the Number”.This is a short Java project that allows the user
   to guess the number generated by the computer & involves the following steps:
   The system generates a random number from a given range, say 1 to 100.
   The user is prompted to enter their given number in a displayed dialogue box.
   The computer then tells if the entered number matches the guesses number or it is
   higher/lower than the generated number.
   The game continues under the user guessing the number.*/

package guessthenumber;

import java.util.Random;
import java.util.Scanner;

public class GuessTheNumber {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();

        int minRange = 1;
        int maxRange = 100;
        int attempts = 0;
        int points = 100; // starting points

        int secretNumber = random.nextInt(maxRange - minRange + 1) + minRange;

        System.out.println("Welcome to Guess the Number game!");
        System.out.println("I've selected a number between " + minRange + " and " + maxRange + ". Guess it!");

        while (true) {
            System.out.print("Enter your guess: ");
            int guess = scanner.nextInt();
            attempts++;

            if (guess == secretNumber) {
                System.out.println("Congratulations! You guessed the number " + secretNumber +
                		" correctly in " + attempts + " attempts.");
                break;
            } else if (guess < secretNumber) {
                System.out.println("Too low! Try again.");
            } else {
                System.out.println("Too high! Try again.");
            }

            if (attempts >= 10) {
                System.out.println("You've reached the maximum number of attempts.");
                break;
            }
        }

        // Display score
        if (attempts == 1) {
            points += 50; // bonus points for guessing in one attempt
        } else if (attempts < 5) {
            points += 20; // bonus points for guessing in less than 5 attempts
        }

        System.out.println("Your final score: " + points);
        scanner.close();
    }
}
